server:
  port: 8083
spring:
  application:
    name: "Reportes"

  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: local-cloud
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  region: "us-east-2"
  dynamodb:
    table-name: "reportes"

adapter:
  sqs:
    region: "us-east-2"
    solicitud-aprobada: "${AWS_SQS_SOLICITUD_APROBADA:https://sqs.us-east-2.amazonaws.com/925323749763/SolicitudAprobadaQueue}"
    reporte-diario: "${AWS_SQS_REPORTE_DIARIO:https://sqs.us-east-2.amazonaws.com/925323749763/ReporteDiarioQueue}"
routes:
  paths:
    reportes-contador: "/api/v1/reportes/total"
    reportes-monto: "/api/v1/reportes/monto"

report:
  cron: ${REPORT_CRON:*/50 * * * * *}
